name: Check Eslint

on: 
  pull_request:
    branches:
      - master

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.17.0
      - name: Innstall Dependencies
        run: yarn
      
      - name: Test Jest
        run: yarn test --coverage