name: CI

on: 
  pull_request:
    branches:
      - master

jobs:
  build: 
    runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      #with: 
          #fetch-depth: 0

    - name: Set Up Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.17.0

    - name: Innstall dependencies
      run: yarn

    - name: Check linting
      run: yarn lint --fix
    
    - name: Check tests
      run: yarn test --coverage

    #- name: Check commit message
      #uses: wagoid/commitlint-github-action@v1